"""Init

Revision ID: d9bdf6b9018b
Revises: 
Create Date: 2023-02-19 11:22:46.537465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bdf6b9018b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_name', sa.String(length=30), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=250), nullable=False),
    sa.Column('student_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('grades',
    sa.Column('mark_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mark_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('students')
    op.drop_table('lessons')
    op.drop_table('teachers')
    op.drop_table('groups')
    # ### end Alembic commands ###
